name: Release

on:
  pull_request:
  push:
    paths:
      - 'pom.xml'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checking out
        uses: actions/checkout@v4

      - id: version-decider
        name: Version Decider
        uses: thiagodnf/version-decider@main
        with:
          file: "${{ github.workspace }}/pom.xml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Creating a new release on Github
        uses: softprops/action-gh-release@v2
        if: steps.version-decider.outputs.new
        with:
          name: v${{ steps.version-decider.outputs.version }}
          tag_name: v${{ steps.version-decider.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}